#!/bin/bash
## Wrapps the SSH command adding support for alias host names.
## 
## Example:
##   :ssh my_server1 [ssh arguments]
## 
## my_server1 is a short made-up alias.  The first time, this command 
## interactivly prompts for the host and user values and saves them for the 
## next runs.  Pay attention to the file name, you can edit that file.
## 
## Examples:
##  
##  SSH to to a remote host:  :ssh dx
##  List a remote directory:  :ssh dx ls
##  List a remote directory:  echo ls|:ssh dx
## 
alias=$1
. $(dirname $0)/prj-env $alias,user,host
user_host=$user${user:+@}$host
shift 1
ssh $user_host $*

