#!/bin/bash
## Prefix standard error lines and standard out lines with some string.
## 
## Usage: errout ./some-script "any parameters"
## 
## By default, prefixes standard error lines with ! and does not prefix 
## standard out lines by anything.  Set the 'error_prefix' or 
## 'out_prefix' variables to customize.
## 
## This is a first layer of simple formatting.  More advanced formatting
## logic (xterm color codes or HTML) may intercept and reformat this 
## output.
## 
error_prefix=${error_prefix:-!}
out_prefix=${out_prefix:-}

# Return value is respected : pipefail
# Standard error and out streams are preserved
# Current environment is inherrited : . "$@"
(set -o pipefail
( (. "$@"|sed "s/^/${out_prefix}/")3>&1 1>&2 2>&3|
  sed "s/^/${error_prefix}/")3>&1 1>&2 2>&3
)
