#!/bin/bash
git_url=${1:-git://example.com/git.git/}
cat <<- EOf

#-f fetch
git remote add -f -t master -m master origin $git_url

#TESTING, set defaults for the push pull commands
cat >> .git/config <<-eof
[branch "master"]
	remote = origin
	merge = refs/heads/master
eof


EOf
