#!/bin/bash
connection_name=${1:-sonicwall}

echo "If you change the configuration files, you'll need to run 'sudo ipsec auto --replace ${connection_name}' to reload the file"

# Clean-up
sudo ipsec setup --stop

sudo ipsec setup --start
test -e /var/run/pluto/pluto.ctl || echo "Wating for pluto.ctl" && sleep 1
test -e /var/run/pluto/pluto.ctl || echo "Wating for pluto.ctl" && sleep 1
test -e /var/run/pluto/pluto.ctl || echo "Wating for pluto.ctl" && sleep 1
test -e /var/run/pluto/pluto.ctl || echo "Wating for pluto.ctl" && sleep 1
test -e /var/run/pluto/pluto.ctl || echo "Wating for pluto.ctl" && sleep 1

set -o xtrace
sudo ipsec auto --add ${connection_name} 
sudo ipsec whack --name ${connection_name} --initiate

