#!/bin/bash

## Run a script and notify based on conditions: 
##  on_output,on_error (one or both)
## 
## Notification is sent using 'mail' to the email address
## provided.  Standard output and standard error are 
## captured together and emailed in the body of the email.
## 

email=${1?Parameter 1 is notification email}
subject=${2?Parameter 2 is the email subject}
options=${3?Parameter 3 Options: on_error,on_output}
cmd=${4?Parameter 4.. commands to execute and watch}

#debugging
#set -o xtrace

tmp=$(mktemp /tmp/notify.XXXXXX)
trap "
  rm -v $tmp
  set +o xtrace
" EXIT

date > $tmp

# >(Process substitution) must be used in place of pipe so $cmd will run
# in this shell giving access to the return code $?.
$cmd > >(tee $tmp) 2>&1 
return_value=$?

date >> $tmp

if 
  [ ! $options ] ||
  ([[ $options == *on_error* ]] && test $return_value -ne 0) ||
  # -s FILE exists and has a size greater than zero
  # on output required a sleep before test -s would work
  ([[ $options == *on_output* ]] && sleep .2 && test -s $tmp)
then
  cat $tmp | mail -s "($return_value) $subject" $email
fi
