#!/bin/bash
## This script may not be accurate
##
## Ubuntu hostname resoluition on Windows
##

#. $(dirname $0)/prj-env smb-properties,windows-domain,windows-domain-server,windows-admin-user

# change 2 settings in smb.conf:
#  workgroup=myworkgroup
#  security=domain (instead of user)

sudo net join -w $windows-domain -S $windows-domain-server -U $windows-admin-user


