#!/bin/bash
## Wrapps the SSH command adding support for alias host names.
## 
## Example:
##   ssh-host my_server1 [ssh arguments]
## 
## my_server1 is a short made-up alias.  The first time, this command 
## interactivly prompts for the host and user values and saves them for the 
## next runs.  Pay attention to the file name, you can edit that file.
## 
## Examples:
##  
##  SSH to to a remote host: ssh-host db
##  List a remote directory: ssh-host db ls
##  List a remote directory: echo ls |ssh-host db
##     Testing return value: echo ls . | ssh-host db && pwd
##     Testing return value: echo ls nowhere | ssh-host db && pwd
## 
alias=$1
. $(dirname $0)/prj-env $alias,user,host
user_host=$user${user:+@}$host
shift 1
ssh $user_host $*

