#!/bin/bash
vm=${1:-WinXP}
cat <<- EOT
# No GUI
vboxmanage startvm $vm --type headless
# Shutdown 
vboxmanage controlvm $vm acpipowerbutton

## Set XP activation paramters
## http://forums.virtualbox.org/viewtopic.php?t=9697#37931
## Probe the machine where your license is activated:
## 
##     sudo dmidecode | less
## 
# Set the following paramters accordingly:
CFG_PATH="VBoxInternal/Devices/pcbios/0/Config"
VSETED="VBoxManage setextradata WinXP"

\$VSETED \$CFG_PATH/DmiBIOSVendor       "Dell Inc."
\$VSETED \$CFG_PATH/DmiBIOSVersion      "A06"
\$VSETED \$CFG_PATH/DmiBIOSReleaseDate  "01/09/2006"
\$VSETED \$CFG_PATH/DmiBIOSReleaseMajor  2
\$VSETED \$CFG_PATH/DmiBIOSReleaseMinor  3
\$VSETED \$CFG_PATH/DmiBIOSFirmwareMajor 2
\$VSETED \$CFG_PATH/DmiBIOSFirmwareMinor 3
\$VSETED \$CFG_PATH/DmiSystemVendor     "Dell Inc."
\$VSETED \$CFG_PATH/DmiSystemProduct    "Precision WorkStation 380"
\$VSETED \$CFG_PATH/DmiSystemVersion    "<EMPTY>"
\$VSETED \$CFG_PATH/DmiSystemSerial     "JJTESTM"
\$VSETED \$CFG_PATH/DmiSystemUuid       "44454C4C-3500-104E-8058-CAC04F473931"
\$VSETED \$CFG_PATH/DmiSystemFamily     "Pentium 4"

EOT

